name: Sync nginx images

on:
  workflow_dispatch:
  schedule:
    # every day at 7am & 7pm pacific
    - cron: "0 2,14 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 20
        env:
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
